#include <stdio.h>
#include <string.h>
void bfi_code(int mem[], char buff[]);
int main(void){
   int mem[65565];
   char buff[255];
   memset(mem, 0, sizeof mem);
   bfi_code(mem, buff);
   return 0;
}
void getInput(int *mem){
   *mem = getchar();
}
void bfi_code(int mem[], char buff[]){
   int i = 0;

	i += 76;
	i += 45;
	mem[i]=0;
	i += 28;
	i += 13;
	mem[i]=0;
	i += 41;
	mem[i]=0;
	i += 16;
	i += 25;
	mem[i]=0;
	i += 1;
	mem[i]=0;
	mem[i] += 27;
	printf("%c", (char)mem[i]);
	mem[i] += 16;
	mem[i] += 48;
	printf("%c", (char)mem[i]);
	mem[i] -= 19;
	printf("%c", (char)mem[i]);
	mem[i] -= 7;
	mem[i] -= 38;
	printf("%c", (char)mem[i]);
	mem[i] += 37;
	mem[i] += 27;
	printf("%c", (char)mem[i]);
	mem[i] -= 41;
	printf("%c", (char)mem[i]);
	mem[i] += 6;
	mem[i] += 18;
	printf("%c", (char)mem[i]);
	mem[i]=0;
	mem[i] += 27;
	printf("%c", (char)mem[i]);
	mem[i] += 26;
	mem[i] += 38;
	printf("%c", (char)mem[i]);
	mem[i] -= 37;
	mem[i] -= 4;
	printf("%c", (char)mem[i]);
	mem[i] += 9;
	printf("%c", (char)mem[i]);
	mem[i] -= 9;
	printf("%c", (char)mem[i]);
	mem[i] += 5;
	printf("%c", (char)mem[i]);
	mem[i] += 17;
	printf("%c", (char)mem[i]);
	mem[i] += 12;
	printf("%c", (char)mem[i]);
	mem[i] += 14;
	mem[i] += 13;
	printf("%c", (char)mem[i]);
	mem[i] += 8;
	printf("%c", (char)mem[i]);
	mem[i] -= 18;
	printf("%c", (char)mem[i]);
	mem[i] += 13;
	printf("%c", (char)mem[i]);
	mem[i] += 1;
	printf("%c", (char)mem[i]);
	mem[i] -= 18;
	mem[i] -= 65;
	printf("%c", (char)mem[i]);
	mem[i] += 10;
	mem[i] += 69;
	printf("%c", (char)mem[i]);
	mem[i] -= 6;
	mem[i] -= 3;
	printf("%c", (char)mem[i]);
	mem[i] -= 70;
	printf("%c", (char)mem[i]);
	mem[i] += 1;
	mem[i] += 39;
	printf("%c", (char)mem[i]);
	mem[i] += 25;
	printf("%c", (char)mem[i]);
	mem[i] += 10;
	mem[i] += 3;
	printf("%c", (char)mem[i]);
	mem[i] += 1;
	printf("%c", (char)mem[i]);
	mem[i] -= 6;
	printf("%c", (char)mem[i]);
	mem[i] -= 63;
	mem[i] -= 10;
	printf("%c", (char)mem[i]);
	mem[i] += 65;
	mem[i] += 8;
	printf("%c", (char)mem[i]);
	mem[i] += 5;
	printf("%c", (char)mem[i]);
	mem[i] -= 61;
	mem[i] -= 17;
	printf("%c", (char)mem[i]);
	mem[i] += 34;
	printf("%c", (char)mem[i]);
	mem[i] += 23;
	mem[i] += 25;
	printf("%c", (char)mem[i]);
	mem[i] -= 17;
	printf("%c", (char)mem[i]);
	mem[i] += 8;
	printf("%c", (char)mem[i]);
	mem[i] += 5;
	printf("%c", (char)mem[i]);
	mem[i] -= 8;
	printf("%c", (char)mem[i]);
	mem[i] -= 8;
	mem[i] -= 52;
	printf("%c", (char)mem[i]);
	mem[i] += 23;
	mem[i] += 34;
	printf("%c", (char)mem[i]);
	mem[i] += 8;
	printf("%c", (char)mem[i]);
	mem[i]=0;
	mem[i] += 27;
	printf("%c", (char)mem[i]);
	mem[i] += 1;
	mem[i] += 63;
	printf("%c", (char)mem[i]);
	mem[i] -= 12;
	mem[i] -= 28;
	printf("%c", (char)mem[i]);
	mem[i] += 8;
	printf("%c", (char)mem[i]);
	mem[i] -= 10;
	printf("%c", (char)mem[i]);
	mem[i] += 4;
	printf("%c", (char)mem[i]);
	mem[i] += 19;
	printf("%c", (char)mem[i]);
	mem[i] += 2;
	mem[i] += 13;
	printf("%c", (char)mem[i]);
	mem[i] += 27;
	printf("%c", (char)mem[i]);
	mem[i] -= 9;
	printf("%c", (char)mem[i]);
	mem[i] += 11;
	printf("%c", (char)mem[i]);printf("%c", (char)mem[i]);
	mem[i] -= 11;
	mem[i] -= 4;
	printf("%c", (char)mem[i]);
	mem[i] += 9;
	printf("%c", (char)mem[i]);
	mem[i] -= 61;
	mem[i] -= 17;
	printf("%c", (char)mem[i]);
	mem[i] += 58;
	mem[i] += 8;
	printf("%c", (char)mem[i]);
	mem[i] += 23;
	printf("%c", (char)mem[i]);
	mem[i] -= 43;
	mem[i] -= 46;
	printf("%c", (char)mem[i]);
	mem[i] += 29;
	mem[i] += 6;
	printf("%c", (char)mem[i]);
	mem[i] += 41;
	printf("%c", (char)mem[i]);
	mem[i] -= 3;
	printf("%c", (char)mem[i]);
	mem[i] -= 3;
	printf("%c", (char)mem[i]);printf("%c", (char)mem[i]);
	mem[i] += 9;
	printf("%c", (char)mem[i]);
	mem[i] += 3;
	printf("%c", (char)mem[i]);
	mem[i] -= 4;
	mem[i] -= 10;
	printf("%c", (char)mem[i]);
	mem[i] -= 65;
	mem[i] -= 3;
	printf("%c", (char)mem[i]);
	mem[i] += 55;
	printf("%c", (char)mem[i]);
	mem[i] += 16;
	mem[i] += 8;
	printf("%c", (char)mem[i]);
	mem[i] -= 3;
	printf("%c", (char)mem[i]);
	mem[i] -= 6;
	printf("%c", (char)mem[i]);
	mem[i] -= 56;
	mem[i] -= 14;
	printf("%c", (char)mem[i]);
	me